// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShortLink = "short_links"

// ShortLink mapped from table <short_links>
type ShortLink struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OriginalURL string    `gorm:"column:original_url;not null" json:"original_url"`
	ShortCode   string    `gorm:"column:short_code;not null" json:"short_code"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName ShortLink's table name
func (*ShortLink) TableName() string {
	return TableNameShortLink
}
